export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_SAVE = 'PRODUCTS_SAVE';
export const FAVOURITES_SAVE = 'FAVOURITES_SAVE';
export const CART_SAVE = 'CART_SAVE';
export const CART_PRODUCT_INCR = 'CART_PRODUCT_INC';
export const CART_PRODUCT_DEC = 'CART_PRODUCT_DEC';